### ISSUE TITLE
SEGFAULT in ompi/opal/mca/btl/smcuda/btl_smcuda.c at *descriptor = NULL

### ISSUE THREAD

**Issue by Stadik** [open-mpi/ompi#10031]
## Background information

OpenMPI versions: 3.0.0, 4.1.0, 4.1.2

All of them installed from source via:
./configure --with-cuda=/usr/local/cuda --prefix=/usr/local/openmpi-<major>.<minor>.<patch>/

Was tested on Ubuntu20.04 and CentOS7 with NVIDIA GTX 1080Ti and NVIDIA RTX 2080 with CUDA 11.0, 11.2, 11.3 and 11.4.

-----------------------------

## Details of the problem

The problem happens when sending asynch. a high number of small message (765 per GPU on 6 processes (6 GPUs)) via ISend + IRecv from global memory on GPU.
I compiled OpenMPI in debug mode via CPPFLAGS=-DDEBUG CFLAGS="-g -O0" and got this backtrace
https://pastebin.com/a7K8jGfF

It seems the issue happens because in ompi/opal/mca/btl/smcuda/btl_smcuda.c at *descriptor = NULL

        /* allocate a fragment, giving up if we can't get one */
        /* note that frag==NULL is equivalent to rc returning an error code */
        MCA_BTL_SMCUDA_FRAG_ALLOC_EAGER(frag);
        if (OPAL_UNLIKELY(NULL == frag)) {
            *descriptor = NULL;
            return OPAL_ERR_OUT_OF_RESOURCE;
        }
        
where descriptor is a NULLPTR but still is dereferenced.
(gdb) print descriptor
$1 = (mca_btl_base_descriptor_t **) 0x0
(gdb) print *descriptor
Cannot access memory at address 0x0

This creates a fatal crash with SIGSEGV without any info of the real issue, which makes it difficult to find what causes it.

Edit: Following the backtrace it seems it will always be a NULLPTR here

    /* try to send immediately */
    rc = mca_bml_base_sendi (bml_btl, &convertor, &match, OMPI_PML_OB1_MATCH_HDR_LEN,
                             size, MCA_BTL_NO_ORDER, MCA_BTL_DES_FLAGS_PRIORITY | MCA_BTL_DES_FLAGS_BTL_OWNERSHIP,
                             MCA_PML_OB1_HDR_TYPE_MATCH, NULL);

**Comment by awlauria** [comment]
This is the same symptom as https://github.com/open-mpi/ompi/issues/9638 - but that is __without__ gpus.

Is it possible that for some reason these gpus are not being detected?

**Comment by Stadik** [comment]
GPUs are detected fine, because I am using another of my libraries where I connect process 0 to all GPUs via threads in ray-tracing code, which is successful.

I am currently doing some extended testing, but it seems I could fix the issue in ompi/opal/mca/btl/smcuda/btl_smcuda.c

I am not clear on how the code handle the message when above 'return OPAL_ERR_OUT_OF_RESOURCE;' is triggered, but the issue seems to be fixed checking for if(descriptor)
In the second code snipped one can see that a hard NULL is passed for the descriptor, so was it maybe never meant to enter this if condition in the first code snippet?

But after adding the checking if the SEGFAULT is gone and doesn't show up even after some million executions.

**Comment by Stadik** [comment]
I can confirm all problem cases are working with this changes. I checked the link @awlauria shared obviously just removing *descriptor = NULL also works.
Will this be fixed in a released patch? This was blocking us for quite some time.

**Comment by jsquyres** [comment]
Fixed by #10088.

**Comment by gpaulsen** [comment]
Re-opening to track for v5.0.x and v4.1.x

**Comment by awlauria** [comment]
v4.0.x: #10145
v4.1.x: #10144
v5.0.x: #10146

**Comment by Stadik** [comment]
Thank you very much for the info. I guess it is not really necessary, but for reasons of completeness I will reply here once we use 4.1.3 and it works with the problem cases.

**Comment by jsquyres** [comment]
@Stadik If you could test with the latest 4.1.x nightly snapshot tarball, that would be great (this fix wasn't included in 4.1.3rc1, but it will definitely be in the release): https://www.open-mpi.org/nightly/v4.1.x/

**Comment by Stadik** [comment]
Of course thanks, I already had checked 4.1.3rc1 source code, so I thought I probably need to wait for the final release, but then I will test that directly 
then.

**Comment by Stadik** [comment]
@jsquyres I will probably have some time to actually run it tomorrow, but I just had a look into https://github.com/open-mpi/ompi/pull/10144
I can see the case with NULL for descriptor is fixed in **[opal/mca/btl/self/btl_self.c](https://github.com/open-mpi/ompi/blob/1db814b2e112fe5472f9feddc6240f1bf8a2b229/opal/mca/btl/self/btl_self.c):249**
but not in **[opal/mca/btl/smcuda/btl_smcuda.c](https://github.com/open-mpi/ompi/blob/1db814b2e112fe5472f9feddc6240f1bf8a2b229/opal/mca/btl/smcuda/btl_smcuda.c):939** which means under cuda (my case) it will still dereference a NULL
I already verified last few weeks (by changing that code myself) that same fix as in btl_self works in btl_smcuda for my issue.

**Comment by jsquyres** [comment]
@bosilca It looks like @Stadik may be correct -- there's another assignment to `*descriptor` that doesn't check whether `descriptor` is NULL or not (on main, and therefore not fixed on the release branches, either):

https://github.com/open-mpi/ompi/blob/1db814b2e112fe5472f9feddc6240f1bf8a2b229/opal/mca/btl/smcuda/btl_smcuda.c#L937-L941

Is there a reason that assignment is ok?  Can you have a look?

**Comment by bosilca** [comment]
I missed to go through the safety check in that `if`. Patch pending.

**Comment by jsquyres** [comment]
* v4.0.x PR: #10177
* v4.1.x PR: #10176 
* v5.0.x PR: #10178

**Comment by Stadik** [comment]
@jsquyres @bosilca I can confirm latest 4.1.x nightly snapshot https://download.open-mpi.org/nightly/open-mpi/v4.1.x/openmpi-v4.1.x-202203300416-0a8d17c.tar.gz solves the issue I described here above.
