### ISSUE TITLE
Wrong received values when using 2 nodes and MPI_indexed datatype

### ISSUE THREAD

**Issue by Iasonaspg** [open-mpi/ompi#11193]
Dear Open-MPI group,

We have come across a strange problem when running our application using 2 nodes. We have found that after calling an `MPI_Alltoallw()` function, some processors have not received the expected values. More specifically, the have received fewer than the expected but with no error.

However, this does not happen always. Until now, we could only reproduce the problem on a 2 nodes setup interconnected with Infiniband. The system has the following OS and kernel version:
> Linux 5.3.0-40-generic #32~18.04.1-Ubuntu SMP Mon Feb 3 14:05:59 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

The execution was successful on a 2 nodes system with:
> Linux 3.10.0-1160.53.1.el7.x86_64 #1 SMP Fri Jan 14 13:59:45 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

We have created a minimal reproducible example that you can find attached [here](https://github.com/open-mpi/ompi/files/10210228/wrong_receive.zip).

### Example explanation

We use 2 processors (1 on each node) with each one having 8000 blocks of 64 MPI_UNSIGNED_LONG numbers. Rank 0 contains only the value 10 whereas rank 1 contains only the value 200. 
We conduct an allgather operation but with different derived datatypes for each process. For this reason, we used both `MPI_Alltoallw()` and a custom implementation using `MPI_Isend()` and `MPI_Irecv()`. The result was the same for both of our experiments.

We would expect than in each processor, the receive buffer will contain only the values 10 and 200 using the cyclic block scheme with a block size of 64. However, in some indices of the receive buffer, no values have been written.

In the attached log file, you can see the output of rank 0. Entries that contain the value 0 and not 10 or 200 indicate that there was a problem in the communication function.

[errlog.0.txt](https://github.com/open-mpi/ompi/files/10210312/errlog.0.txt)

We are eager to help as much as we can to identify and resolve this problem, in the case that it is a bug and not an error that we have done.

Best regards,
Jason

**Comment by bosilca** [comment]
@Iasonaspg unfortunately this is a known behavior for some collective algorithms when different processes provide different datatypes. The root cause is that some of the underlying collective algorithms do internal pipelining using a segment size of multiple of the user-provided datatype. When multiple datatypes are involved datatypes, different processes might decide to split the data differently resulting in inconsistencies. In general it leads to memory corruptions and segfaults, but in your case just to incorrect data.

There are two solutions here, but none of them is portable. You can use the MCA parameters to prevent pipelining for the collectives where you notice data corruption, or you can use MPI_Info to inform the communicators where these operations will happen to prevent pipelining. In both cases, it might result in sub-optimal collectives, but at least the data will remain correctly transferred in all cases.

**Comment by Iasonaspg** [comment]
> @Iasonaspg Thanks for the report. I ran reproducer on my local shared memory system and couldn't reproduce it (not surprising, given your description).
> 
>     * What Open MPI version are you using?
> 
>     * Are you using UCX? Which version?
> 
>     * What is the interconnect of the second system that does not show the problem?
> 
> 
> With that information we can try to isolate specific components.

Thank you for your response,

* We are using `Open MPI 4.1.1`
* Yes, we are using `UCX 1.11.2`
* The second system that has no probelm is interconnected with an Ethernet switch. It has Infiniband interfaces but are disconnected.

We have also used UCX 1.13 and MPI 4.1.2 but the problem was the same.

We just found that `Open MPI 3.1.6 + UCX 1.9` is **working**. I will try Open MPI 3.1.6 + UCX 1.13 to see if the problem lies in the UCX library. Otherwise, it may be a change from Open MPI 3.1.6 to Open MPI 4.1.x

**Comment by devreal** [comment]
@Iasonaspg Could you try Open MPI 4.1.4 (the latest release in that series) on the Infiniband system? Maybe the problem is already fixed. If that still yields incorrect results, could you pass `--mca pml ^ucx` to `mpirun`? I suspect that the UCX integration is to blame so let's try disabling it.

**Comment by Iasonaspg** [comment]
@devreal  I just ran with Open MPI 4.1.4 + UCX 1.13. I also passed `--mca pml ^ucx` but the results are still incorrect. Furthermore, I noticed that our MPI build cannot run if I specify `--mca pml ucx`.

This error is printed
> No components were able to be opened in the pml framework

Does this indicate that we did not build correctly Open MPI to use UCX? 
In general, we run without specifying mca parameters. We supposed that Infiniband was indeed used due to no observed performance overhead between 1 and 2 nodes execution.

**Comment by bosilca** [comment]
I am unable to reproduce with the current master and a current UCX. I went back to the example, and I noticed that it does not use displacement for receives, but instead it adds the displacement into the datatype itself. Is this the same as your original code ?

**Comment by Iasonaspg** [comment]
@bosilca Yes, this is something that we usually do. Is it a bad technique?

**Comment by bosilca** [comment]
It is correct, but suboptimal. All datatypes are identical (same count and same array of blocklen), with the only difference being that you shift the displacements by `cyclic_block` for all but the first datatype). The shift of the displacement can be done using the receive displacements in the `alltoallw`, and it will allow you to only have to build one single datatype.

Btw, I noticed while writing this that you might not be correctly building your datatype. The displacement for all but the first element increases by `comm_size * cyclic_block`, signaling that you you jump in your data according to the number of processes in the communicator. However, the initial displacement is the same for all but rank 0, because you set it to `cyclic_block`. Should this be `i * cyclic_block` to incorporate the rank of the target into the displacement ?

**Comment by Iasonaspg** [comment]
@bosilca Yes, you are correct about the suboptimality of our choice for this example. However, it is quite rare that all the processors will have the exact same number of blocks with equal block size. We wanted a simplified version for readability and understanding.

Your observation is correct but we are using only 2 processors for this example. So the first one has displacement 0 and the second one has cyclic_block.
