### ISSUE TITLE
mpi4py: intercomm_create_from_groups can hang in certain scenarios

### ISSUE THREAD

**Issue by dalcinl** [open-mpi/ompi#11593]
The testsuite [hangs until timeout](https://github.com/mpi4py/mpi4py-testing/actions/runs/4710568790/jobs/8354327433). This happens only with `main`. Runs from yesterday were fine.

**Comment by dalcinl** [comment]
@jsquyres @rhc54 The regression comes from #11408.

**Comment by rhc54** [comment]
I'm afraid I don't know anything about your test suite. Precisely what test were you running, how was it executed, etc?

**Comment by dalcinl** [comment]
@rhc54 I've asked many times for mpi4py to be integrated into Open MPI test infrastructure. I even offered a ready to use workflow working GitHub Actions. Unfortunately, it never happened, I never got a plain answer for yes or no. At this point I think it is some political issue, but no one wants to say that in the open (or even in private). Open MPI issue reports from mpi4py users have made my life miserable over the years, with regressions every other patch release. I'm doing the only thing slightly less miserable for me: run against v5.0.x and main, and submit an issue here every time there is a failure, to prevent mpi4py users a broken Open MPI reaching to their hand. I either do that, or I say all my users: mpi4py no longer supports Open MPI, and offload all my misery to the Open MPI team. Sorry for the rant, you have nothing to do with it, but sometimes I get really frustrated.

Running mpi4py testsuite is pretty easy. Just copy&paste the following hunk. Everything will happen in a Python virtual environment created under `/tmp`, so no modifications to your system afterwards.
```
cd /tmp
git clone --depth 1 https://github.com/mpi4py/mpi4py.git
python3 -m venv /tmp/venv
source /tmp/venv/bin/activate
pip install ./mpi4py
export CFLAGS="-O0 -Wp,-U_FORTIFY_SOURCE"
mpiexec -n 2 python3 ./mpi4py/test/main.py -v -k TestCommWorld.testCreateFromGroup
```
The last `-k ...` argument is to run a particular test, which is the one that is failing (it hangs forever). 

And then, by looking at the failing test, the following Python code is a minimal reproducer:
```python
from mpi4py import MPI
group = MPI.COMM_WORLD.Get_group()
comm = MPI.Intracomm.Create_from_group(group)
```
Put these three lines in a `reproducer.py` file, next run:
```
mpiexec -n 2 python3 reproducer.py 
```
and it hangs for ever.

`MPI_Comm_create_from_groups` is typically used with `MPI_Group`s out of `MPI_Session`s, but IIRC there is nothing in the MPI-4.0 standard that prevent us from using the routine with a group that comes from a communicator. My wild guess is that there is some issue/oversight that triggered after the PMIx/PRRTE submodule bump. If that endup being the case, then I'm sorry @rhc54, this would be the second time I ping you for things you are ultimately not responsible for.

@hppritcha Maybe you should take a look into this issue.

**Comment by rhc54** [comment]
Yeah, ranting at me doesn't accomplish anything. First, I'm not part of the OMPI community - and second, I'm retired. OMPI just uses a couple of my software packages.

I can't take on different test suites as there are several, no clear reason to favor one over the other - and I have limited time. Besides, I support multiple MPI and other programming model libraries, and I'd drown if I tried to get that deeply involved in any one of them. Sorry, I know that isn't an answer one wants to hear, but it's the reality. Which is why I need to know what was being tested.

As for this problem: it probably isn't something to do with PRRTE as mostly PRRTE just starts the procs. It _might_ have something to do with PMIx if MPI is getting some PMIx-provided data and has a problem getting it, or is calling something like PMIx_Group (which could extend up into a call to PRRTE) and hits a problem. I honestly don't know anything about what OMPI is doing in that function, so somebody over there will have to investigate and let me know if something is amiss on my side.

**Comment by dalcinl** [comment]
> Yeah, ranting at me doesn't accomplish anything.

Well, I'm not native English speaker, and I'm not sure the exact meaning of "ranting at me". I said in my comment: *you have nothing to do with it*. I'm aware you are not part for OMPI. I'm having trouble to manage my frustration. Probably I'm being victim of the usal open-source mainter burnout syndrome, and I resist to acknowledge it and move away for good.

> I can't take on different test suites as there are several, no clear reason to favor one over the other.

Well, perhaps you do not ultimately care about MPI testing, but just FYI: mpi4py can build and run its tests  in about one minute in bare metal (`CFLAGS=-O0`, `mpiexec -n 2 ...`). The testsuite covers almost all of MPI-4.0, uses the new large-count APIs exclusively if available, and all tests run in a single mpiexec execution, so it can potentially catch (and have catched in the past) internal MPI components not playing well each other.

**Comment by hppritcha** [comment]
@dalcinl i'll take a look and yes it would be good to add the mpi4py testsuite to a reliable MTT platform.  I'll add both to my enormous todo list for this week.

**Comment by awlauria** [comment]
How long does the mpi4py bucket take to run? With how many breakages we have it might be better to put these in a CI test.

**Comment by dalcinl** [comment]
@hppritcha Sorry for my insistence, but mpi4py test suite have been failing for about two weeks. I'm just worried that the failure from this know issue may be masking other potential regressions as main keeps accumulating changes.

**Comment by dalcinl** [comment]
> I assume you meant the `main` branch.

Yes, of course. I should have said *... as the main branch keeps accumulating changes.*

> The `master` branch is no more updated and lags behind the `main` branch by more than one year.

I did not mention the master branch. I'm aware that master is no longer active.

> (I am unable to run the script you provided as-is)

Well, yes, you would have to install mpi4py for that. But I guess people can find that step cumbersome.

> FWIW, I was able to run the following C program

Your program does not use the broken MPI routine I'm reporting. You are testing  `MPI_Comm_create_group`, but it should be `MPI_Comm_create_from_group`. This is the proper reproducer:

```c
#include <mpi.h>

int main(int argc, char *argv[]) {
    MPI_Init(&argc, &argv);
    MPI_Group group;
    MPI_Comm_group(MPI_COMM_WORLD, &group);
    MPI_Comm comm;
    MPI_Comm_create_from_group(group,
                               "org.example",
                               MPI_INFO_NULL,
                               MPI_ERRORS_ARE_FATAL,
                               &comm);
    MPI_Group_free(&group);
    MPI_Comm_free(&comm);
    MPI_Finalize();
    return 0;
}
```

> The `mpi4py` test suite can definitely help notice regressions, but from a very pragmatic point of view,
> I am afraid this is only what it does.
> The next step (from an Open MPI developer) is to isolate the test case and write a `C` reproducer.

So are you complaining about the inconvenience of writing a C reproducer because you don't want to use Python?  
Is an unnoticed regression preferable?

> In this very specifc case it looked like an easy one so I tried it and ... I was unable to reproduce the hang.

Well, it was an easy one indeed, you just confused the routine to test because of the very similar names.

**Comment by ggouaillardet** [comment]
My bad: my`mpi4py` tree was still pointing to bitbucket.org and was out of date, that's why I missed the right subroutine.

My point is `python/mpi4py` adds an extra layer that generally does not fly well with debuggers, so a C reproducer is way easier for troubleshooting.

FWIW, on my mac,
 - the `C` test passes
 - the `mpi4py` does not hang but fails on `self.assertEqual(ccmp, MPI.CONGRUENT)`
    in `C`, comparison returns `MPI_IDENT` and I guess `MPI_CONGRUENT` is expected.

**Comment by hppritcha** [comment]
@dalcinl you are still observing the test timeout problem, correct?  would the assert test failing cause this timeout behavior?
I will have some time this week to look at this.

**Comment by dalcinl** [comment]
@hppritcha Yes, the issue persists. Besides the GitHub Actions failure 16 hours ago, I tested locally on Linux with `ompi@main` a couple hours ago using the pure C reproducer I pasted in my previous comment (note there is no comm comparison in the C reproducer).

@ggouaillardet Are you talking about the assertion in the `testCreateFromGroup()` test method? If yes, then I believe that would also be a bug:  `MPI_Comm_create_from_group` should not return a communicator handle that compares as `MPI_IDENT` with the existing communicator from which the group was obtained. Looks like this finding of yours is just another signal of things being off. Oh, after re-reading your comment, I think that's what exactly what you meant with `MPI_CONGRUENT` being expected.

**Comment by hppritcha** [comment]
okay, i think the ident verses congruent is a different problem.  odd but I thought we fixed that before.

**Comment by hppritcha** [comment]
@dalcinl not a big deal but if i follow the directions for running just a failing test i get:
```
venv) localhost:/tmp$ mpirun --map-by :OVERSUBSCRIBE -np 2  python3 ./mpi4py/test/main.py -v -k TestCommWorld.testCreateFromGroup
usage: main.py [-h] [-v] [-q] [--locals] [-f] [-c] [-b] [-i REGEX] [-e REGEX]
               [--no-builddir] [--path PATH] [--threads] [--no-threads]
               [--thread-level LEVEL] [--cupy] [--no-cupy] [--numba]
               [--no-numba] [--no-numpy] [--no-array] [--no-skip-mpi]
               [tests [tests ...]]
main.py: error: unrecognized arguments: -k
usage: main.py [-h] [-v] [-q] [--locals] [-f] [-c] [-b] [-i REGEX] [-e REGEX]
               [--no-builddir] [--path PATH] [--threads] [--no-threads]
               [--thread-level LEVEL] [--cupy] [--no-cupy] [--numba]
               [--no-numba] [--no-numpy] [--no-array] [--no-skip-mpi]
               [tests [tests ...]]
main.py: error: unrecognized arguments: -k
--------------------------------------------------------------------------
prterun detected that one or more processes exited with non-zero status, thus causing
the job to be terminated. The first process to do so was:

  Process name: [prterun-localhost-79193@1,1]
  Exit code:    2
--------------------------------------------------------------------------
```

**Comment by ggouaillardet** [comment]
I am unable to reproduce the issue on my Linux VM (no hang, `MPI_CONGRUENT` is "returned").

That being said, on my mac, there is no hang bug `MPI_IDENT` is returned and I opened #11633 in order to address this.

Unless I messed up, my both systems use the embedded `PMIx` (both up-to-date `main` branch and submodules)
I do not explain the different behavior (`PMIx_Group_construct()` returns one info on Linux and two on OSX and to be honest, I did not search)

@dalcinl can you please give this PR a try? are you using an external `PMIx`?

**Comment by rhc54** [comment]
> I do not explain the different behavior (PMIx_Group_construct() returns one info on Linux and two on OSX

Not entirely sure why that would be true - was this running on one node or multiple? How many procs?

**Comment by rhc54** [comment]
Sorry - should have posted this comment here:

@ggouaillardet Perhaps you could have one proc print out the keys that are returned in both environments? Might help to ensure we are looking at the same thing.

**Comment by ggouaillardet** [comment]
on OSX, there are two infos with keys

- `pmix.grp.mbrs`
- `pmix.grp.ctxid`

only the latter on Linux.

**Comment by rhc54** [comment]
Hmm...you should always get both of those keys. I'll have to look at Linux to see why it is missing the other one.

**Comment by ggouaillardet** [comment]
I am sorry there was something wrong with my environment (!)

I ran `make install` so many times, but it seems an old  PMIx was installed and i found out when I finally decided to manually run `make install` in `3rd-party/openpmix`

both infos are now available on Linux.

**Comment by rhc54** [comment]
Thanks - I kind of figured that was the case 😄

**Comment by rhc54** [comment]
Just curious - was anyone able to reproduce the hang reported here? I'm not sure I understand why the fix in #11635 would resolve a hang.

**Comment by hppritcha** [comment]
#11635 and #11633 fix this.
I would note that at least one of the pmix examples using PMIx_Group_construct requires a similar change to what was done in these PRs.

**Comment by dalcinl** [comment]
@hppritcha mpi4py testsuite [still hangs](https://github.com/mpi4py/mpi4py-testing/actions/runs/4867100609/jobs/8679339681) with main, although this time the issue is with the different but related routine `MPI_Intercomm_create_from_groups`. These tests need at least three MPI processes to run, otherwise they are skipped.

The issue is a bit hard to reproduce, it took me a while to come up with a minimal reproducer. It is somehow related to use the same `stringtag` value in successive calls. I'm attaching a Python reproducer you can easily run (just remove the .txt extension GitHub forces me to add). 

[test-intercomm-group.py.txt](https://github.com/open-mpi/ompi/files/11379964/test-intercomm-group.py.txt)

First run it the following way, you need 3 MPI processes or more:
```
$ mpiexec -n 3 python test-intercomm-group.py
Test Half
Test Pair
<deadlock>
```
and it will deadlock

Next run it with the `TAG` env var set to any nonempty string to use a different tag value in the second invocation to `MPI.Intercomm.Create_from_groups()`. 

$ env TAG=x mpiexec -n 3 python test-intercomm-group.py
Test Half
Test Pair
```
By design of the test, the second invocation of `MPI.Intercomm.Create_from_groups()` happens only in process 0 and 1, but not 2. If you add a few extra `print` calls, you will see that neither process 0 nor process 1 ever exit.

Please note that I've added double-barriers on `COMM_WORLD` after each test block, and I'm not using threads (although MPI is initialized with THREAD_MULTIPLE). Therefore, I'm not calling `MPI.Intercomm.Create_from_groups()` concurrently in any way, so using the same `stringtag` value for each call should work just fine. At least, that's what I understand from my reading of the MPI standard.

**Comment by hppritcha** [comment]
the intercomm_create_from_groups has known issues.  I would suggest disabling this section of the test, at least for open mpi until that problem has been corrected.  Turns out it wasn't implemented correctly the first time.  I thought I had an issue open on this but apparently not.

**Comment by dalcinl** [comment]
@hppritcha I'm not sure what's the status of this issue. Should it be closed, or is the root known issue still around?

**Comment by hppritcha** [comment]
fixed via various commits.
