### ISSUE TITLE
host order -dependent "num local peers" failure

### ISSUE THREAD

**Issue by jwagnerhki** [open-mpi/ompi#12136]
Thank you for taking the time to submit an issue!

### What version of Open MPI are you using? (e.g., v3.0.5, v4.0.2, git branch name and hash, etc.)

 v4.1.2, v4.1.6, v5.0.0

### Describe how Open MPI was installed (e.g., from a source/distribution tarball, from a git clone, from an operating system distribution package, etc.)

From tarball. Configuration was

```
$ ./configure --enable-heterogeneous --prefix=/opt/openmpi/4.1.6/ --with-knem=/opt/knem/1.1.3 \
  --enable-orterun-prefix-by-default --with-slurm --without-tm --without-ofi --with-pmix --with-knem=/opt/knem/1.1.3/ \
  --enable-cxx-exceptions --enable-mpi1-compatibility --with-verbs --without-psm2 --with-psm

$ ./configure --enable-heterogeneous --prefix=/cluster/openmpi/5.0.0/ --with-knem=/opt/knem/1.1.3 \
     --enable-orterun-prefix-by-default --with-slurm --without-tm --without-ofi --with-pmix --with-knem=/opt/knem/1.1.3/ \
     --with-verbs --without-psm2 --with-psm
```
### Please describe the system on which you are running

* Operating system/version: CentOS 7
* Computer hardware: heterogenous Intel CPU -based cluster with separate data storage nodes
* Network type: InfiniBand FDR, 1 GbE

-----------------------------

## Details of the problem

Under all tested OpenMPI versions, mpirun with a host file fails to set up MPI, terminating at MPI_Init() with the Open MPI error,

```num local peers --> Returned "Bad parameter" (-5) instead of "Success" (0)```

The host file in our case can have multiple entries for the same machine, since the behavior of the binary program depends on mpi rank. Furthermore our cluster is heterogenous/asymmetric in that only certain nodes have access to certain local data. Thus the order of entries in the machines file is critical. We thus normally run with "--rmaps seq", however, the num local peers issue is triggered also without that parameter.

If one takes the host file and sorts it alphabetically, however, the same job succeeds. 

An alphabetic sort is fine for "hello world" type test programs, but unfortunately not for our production application, where process placement is critical.

How to fix the "num local peers" error? And why does it depend on the order of entries in the machines file? 

Does openmpi launch processes sequentially rather than in parallel? Is there a timeout in openmpi code, giving up too soon in the check for locally reachable instances of the program, that are still to be launched further down the sequential(?) launch order?

Many thanks in advance.

Longer summary:
 
```
$ mpirun -np 44 --hostfile failing.machines /cluster/test/bin/mpihelloworld
... 
--------------------------------------------------------------------------
It looks like MPI runtime init failed for some reason; your parallel process is
likely to abort.  There are many reasons that a parallel process can
fail during RTE init; some of which are due to configuration or environment
problems.  This failure appears to be an internal failure; here's some
additional information (which may only be relevant to an Open MPI
developer):

  num local peers
  --> Returned "Bad parameter" (-5) instead of "Success" (0)
--------------------------------------------------------------------------

$ sort failing.machines > sorted.machines
$ mpirun -np 44 --hostfile sorted.machines /cluster/test/bin/mpihelloworld
fxmanager : Rank 14 numprocs 44
fxmanager : Rank 12 numprocs 44
fxmanager : Rank 15 numprocs 44
fxmanager : Rank 13 numprocs 44
fxmanager : Rank 2 numprocs 44
fxmanager : Rank 1 numprocs 44
fxmanager : Rank 11 numprocs 44
fxmanager : Rank 3 numprocs 44
fxmanager : Rank 0 numprocs 44
fxmanager : Rank 9 numprocs 44
fxmanager : Rank 6 numprocs 44
fxmanager : Rank 10 numprocs 44
fxmanager : Rank 5 numprocs 44
fxmanager : Rank 7 numprocs 44
fxmanager : Rank 8 numprocs 44
fxmanager : Rank 4 numprocs 44
io01 : Rank 16 numprocs 44
io07 : Rank 43 numprocs 44
io01 : Rank 18 numprocs 44
...

$ cat failing.machines 
fxmanager
mark6-08
mark6-08
io18
mark6-10
mark6-10
io01
io01
io16
io01
io02
io07
io08
io09
node02
node03
node04
node05
node06
node07
node08
node09
node10
node11
node12
node13
node14
node15
node16
node17
node18
node19
node20
node21
node22
node23
node24
node25
node26
node27
node28
node29
node30
node31

$ cat sorted.machines
fxmanager
io01
io01
io01
io02
io07
io08
io09
io16
io18
mark6-08
mark6-08
mark6-10
mark6-10
node02
node03
node04
node05
node06
node07
node08
node09
node10
node11
node12
node13
node14
node15
node16
node17
node18
node19
node20
node21
node22
node23
node24
node25
node26
node27
node28
node29
node30
node31
```

**Comment by rhc54** [comment]
The error means that the local rank of the proc is greater than the number of procs on that node - what that has to do with the alphabetical order of the hostfile is beyond my understanding. I'm not sure there is a way to easily reproduce it either, so this may wind up having to wait some time before being addressed. Will have to ponder.

Meantime, seems you have a pretty simple workaround.

**Comment by rhc54** [comment]
Couple of questions:

* when you say "heterogeneous", what exactly do you mean? I'm pretty sure that `--enable-heterogeneous` the way we meant it doesn't work any more, so it would help to know how you were using it.
* What process placement were you attempting to achieve? It looks like you wanted 1 proc/node, and you want them in the order of the host names? If so, why aren't you using the sequential mapper?

**Comment by rhc54** [comment]
Here is something you might try with OMPI v5 - add `PMIX_MCA_preg=compress` to your environment. This is assuming you have `zlib` on your machines. If you don't, then you might try `PMIX_MCA_preg=raw`.

**Comment by rhc54** [comment]
> Is there any PMIX_MCA_preg counterpart in OMPI v4.1?

Try `OMPI_MCA_regx=naive`

> regarding slow-down

Thanks for the info! There is a known bug in OMPI v5.0.0 that causes the old ORTE params to not be translated to their new PRRTE equivalents. Should be fixed for the next release.

**Comment by jwagnerhki** [comment]
Thanks, alas, under v4.1 had no luck with `OMPI_MCA_regx=naive` and we are still getting the "num local peers" error there.

Under OMPI v5.0.0, things now finally work after using `--map-by seq` "job failed to map" (https://github.com/openpmix/prrte/pull/1863), MCA preg compress, and some additional env settings to recover Mellanox ConnectX-3 Infiniband support after loss of openib support in favour of verbs+libfabric in OMPI v5 in favor of libfabric.

```
# Settings for OMPI v5.0.0+patch
export PMIX_MCA_preg=compress  # avoids "num local peers" error
export OMPI_MCA_pml=ob1        # avoids fi_getinfo mtl_ofi_component.c:737 Error: Function not implemented (38)
export TMPDIR=/tmp/

# Additional mpirun parameters to permit data over Infiniband
export DIFX_MPIRUNOPTIONS="$DIFX_MPIRUNOPTIONS --mca btl_ofi_provider_include verbs --mca mtl_ofi_provider_include verbs"
export DIFX_MPIRUNOPTIONS="$DIFX_MPIRUNOPTIONS --mca btl_tcp_if_include 10.10.0.0/8  --mca oob_tcp_if_include 10.10.0.0/8" # ConnecX-3 10.12.x.x/16 ib0 + eth0 1 GbE 10.10.x.x/16
``` 

Many thanks for your help!
