### ISSUE TITLE
MPI_T_finalize() gets SEGV when called

### ISSUE THREAD

**Issue by rolfv** [open-mpi/ompi#374]
This problem happens on the master only.  Issue is not seen on 1.8 series.

```
[rvandevaart@drossetti-ivy5 nv]$ mpicc -Wall -g simplest_tool.c -o simplest_tool
[rvandevaart@drossetti-ivy5 nv]$ gdb ./simplest_tool
GNU gdb (GDB) Red Hat Enterprise Linux (7.2-60.el6_4.1)
Copyright (C) 2010 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.


This GDB was configured as "x86_64-redhat-linux-gnu".
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>...
Reading symbols from /ivylogin/home/rvandevaart/tests/ompi-tests-git/nv/simplest_tool...done.
(gdb) run
Starting program: /ivylogin/home/rvandevaart/tests/ompi-tests-git/nv/simplest_tool 
[Thread debugging using libthread_db enabled]
[drossetti-ivy5.nvidia.com:27022] [[INVALID],INVALID] ORTE_ERROR_LOG: Error in file ../../../../../orte/mca/ess/pmi/ess_pmi_component.c at line 83
[New Thread 0x7ffff53db700 (LWP 27025)]
[New Thread 0x7fffeb2e2700 (LWP 27027)]
MPI_T_init_thread() ret=0, provided=0
MPI_T_cvar_get_num ret=0, num_cvar=1210
MPI_T_pvar_get_num ret=0, num_pvar=2
[Thread 0x7fffeb2e2700 (LWP 27027) exited]
[Thread 0x7fffec2e3700 (LWP 27026) exited]
[Thread 0x7ffff53db700 (LWP 27025) exited]

Program received signal SIGSEGV, Segmentation fault.
0x00007ffff6f1dce4 in var_destructor (var=0x6ed260) at ../../../../opal/mca/base/mca_base_var.c:1735
1735	        NULL != var->mbv_storage->stringval) {
(gdb) where
#0  0x00007ffff6f1dce4 in var_destructor (var=0x6ed260) at ../../../../opal/mca/base/mca_base_var.c:1735
#1  0x00007ffff6f19901 in opal_obj_run_destructors (object=0x6ed260) at ../../../../opal/class/opal_object.h:446
#2  0x00007ffff6f1bc41 in mca_base_var_finalize () at ../../../../opal/mca/base/mca_base_var.c:1041
#3  0x00007ffff6edb550 in opal_finalize_util () at ../../opal/runtime/opal_finalize.c:83
#4  0x00007ffff7ad3258 in ompi_mpi_finalize () at ../../ompi/runtime/ompi_mpi_finalize.c:443
#5  0x00007ffff7afbda5 in PMPI_Finalize () at pfinalize.c:46
#6  0x0000000000400820 in main (argc=1, argv=0x7fffffffe548) at simplest_tool.c:27
(gdb) 
```

**Comment by rolfv** [comment]
Here is the program:
```
/*
 * Tools interface test to dump all existing cvars and pvars
 */

#include <stdio.h>
#include <stdlib.h>
#include <mpi.h>

#define STRINGIFY(x) #x
#define BUFSIZE 1024 /* Just pick some size to hold most everything */

int key1;
int stream = -1;
int *stream2 = NULL;
int flag = 0, ret = 0;
void **attrp;
int sstrm, rstrm;
int num_no_object = 0;

void tool_test(void);
char *pretty_print_bind(int);

int main(int argc, char* argv[])
{
    MPI_Init(&argc, &argv);
    tool_test();
    MPI_Finalize();
    return 0;
}

void tool_test(void) {
  int ret;
  int num_cvar, num_pvar;
  int provided;

  ret =  MPI_T_init_thread(MPI_THREAD_SINGLE, &provided);

  printf("MPI_T_init_thread() ret=%d, provided=%d\n", ret, provided);
  /* Control variables */
  ret = MPI_T_cvar_get_num(&num_cvar);
  printf("MPI_T_cvar_get_num ret=%d, num_cvar=%d\n", ret, num_cvar);
  /* Performance variables */
  ret = MPI_T_pvar_get_num(&num_pvar);
  printf("MPI_T_pvar_get_num ret=%d, num_pvar=%d\n", ret, num_pvar);

  /* If you comment this out, then the test will pass. */
  MPI_T_finalize();  
}
```

**Comment by hppritcha** [comment]
@hjelmn  assigning this to Nathan.

**Comment by hjelmn** [comment]
More that likely this is due to a variable value being freed out from under the MCA variable system. Let me see if I can track down the culprit.

**Comment by hjelmn** [comment]
Hmm, the responsible component does not appear in my build. Can you print out the value of var->mbv_full_name?

**Comment by rolfv** [comment]
```
(gdb) up
#2  0x00007ff865d26e30 in var_destructor (var=0x26c5cb0) at ../../../../opal/mca/base/mca_base_var.c:1735
1735	        NULL != var->mbv_storage->stringval) {
(gdb) print var
$1 = (mca_base_var_t *) 0x26c5cb0
(gdb) print var->mbv_full_name
$2 = 0x26c5e00 "mtl_ofi_provider"
(gdb) 
```

**Comment by jsquyres** [comment]
@yburette Can you have a look?  It looks like the storage for this MCA parameter is being deleted too early.

**Comment by hjelmn** [comment]
Yup. No strings associated with an MCA variable should ever be freed outside the MCA system.

**Comment by jsquyres** [comment]
@yburette This might fix the problem...?

```diff
diff --git a/ompi/mca/mtl/ofi/mtl_ofi_component.c b/ompi/mca/mtl/ofi/mtl_ofi_com
index b6004a7..40aee0c 100644
--- a/ompi/mca/mtl/ofi/mtl_ofi_component.c
+++ b/ompi/mca/mtl/ofi/mtl_ofi_component.c
@@ -161,7 +161,7 @@ ompi_mtl_ofi_component_init(bool enable_progress_threads,
      */
     domain_attr.threading        = FI_THREAD_ENDPOINT;
     domain_attr.control_progress = FI_PROGRESS_AUTO;
-    fabric_attr.prov_name        = ompi_mtl_ofi.provider_name;
+    fabric_attr.prov_name        = strdup(ompi_mtl_ofi.provider_name);
     hints.domain_attr            = &domain_attr;
     hints.fabric_attr            = &fabric_attr;
 
```

**Comment by jsquyres** [comment]
Fixed in open-mpi/ompi@030e9bc714f9ea51130bfea71dbb0d9139e7d615.

**Comment by rolfv** [comment]
I just retested with the latest master and things are still broken for me.
```
(gdb) where
#0  0x00007ff4d6b0b1d0 in ?? ()
#1  <signal handler called>
#2  0x00007ff4ebc5e46f in var_destructor (var=0x14b7360) at ../../../../opal/mca/base/mca_base_var.c:1740
#3  0x00007ff4ebc5a061 in opal_obj_run_destructors (object=0x14b7360) at ../../../../opal/class/opal_object.h:446
#4  0x00007ff4ebc5c389 in mca_base_var_finalize () at ../../../../opal/mca/base/mca_base_var.c:1040
#5  0x00007ff4ebc1bb44 in opal_finalize_util () at ../../opal/runtime/opal_finalize.c:83
#6  0x00007ff4ecea82b4 in ompi_mpi_finalize () at ../../ompi/runtime/ompi_mpi_finalize.c:443
#7  0x00007ff4eced0e59 in PMPI_Finalize () at pfinalize.c:46
#8  0x0000000000401050 in main (argc=1, argv=0x7fff782411d8) at tools_test.c:18
(gdb) up
#1  <signal handler called>
(gdb) up
#2  0x00007ff4ebc5e46f in var_destructor (var=0x14b7360) at ../../../../opal/mca/base/mca_base_var.c:1740
1740	        NULL != var->mbv_storage->stringval) {
(gdb) print var->mbv_storage->stringval
Cannot access memory at address 0x7ff4d73d2c90
(gdb) print var->mbv_full_name
$1 = 0x14b7480 "mtl_ofi_provider"
(gdb) print *var
$2 = {super = {obj_magic_id = 0, obj_class = 0x7ff4ebf1b8c0, obj_reference_count = 0, 
    cls_init_file_name = 0x7ff4ebce4268 "../../../../opal/mca/base/mca_base_var.c", cls_init_lineno = 1289}, mbv_index = 723, 
  mbv_group_index = 143, mbv_info_lvl = OPAL_INFO_LVL_4, mbv_type = MCA_BASE_VAR_TYPE_STRING, 
  mbv_variable_name = 0x14b7460 "provider", mbv_full_name = 0x14b7480 "mtl_ofi_provider", 
  mbv_long_name = 0x14b74a0 "mtl_ofi_provider", mbv_synonyms = {super = {obj_magic_id = 16046253926196952813, 
      obj_class = 0x7ff4ebf1ab20, obj_reference_count = 1, 
      cls_init_file_name = 0x7ff4ebce4268 "../../../../opal/mca/base/mca_base_var.c", cls_init_lineno = 1727}, 
    array_items = 0x14b7440 "\330/\362\353\364\177", array_item_sizeof = 4, array_size = 0, array_alloc_size = 1}, mbv_flags = 65600, 
  mbv_scope = MCA_BASE_VAR_SCOPE_READONLY, mbv_source = MCA_BASE_VAR_SOURCE_DEFAULT, mbv_synonym_for = -1, 
  mbv_description = 0x14b6910 "Name of OFI provider to use", mbv_source_file = 0x0, mbv_enumerator = 0x0, mbv_bind = 0, 
  mbv_storage = 0x7ff4d73d2c90}
(gdb) 
```

**Comment by yburette** [comment]
Hi Rolf,

For some reason, I am not able to reproduce the error on my side. I'm using the test you posted above.

Are you passing any special parameter? What am I missing?

Yohann

```
mpirun --mca mtl_base_verbose 100 --host h-18,h-19 -n 2 ./test
[h-19:16232] mca: base: components_register: registering mtl components
[h-19:16232] mca: base: components_register: found loaded component ofi
[h-19:16232] mca: base: components_register: component ofi register function successful
[h-19:16232] mca: base: components_register: found loaded component psm
[h-19:16232] mca: base: components_register: component psm register function successful
[h-19:16232] mca: base: components_open: opening mtl components
[h-19:16232] mca: base: components_open: found loaded component ofi
[h-19:16232] mca: base: components_open: component ofi open function successful
[h-19:16232] mca: base: components_open: found loaded component psm
[h-19:16232] mca: base: components_open: component psm open function successful
[h-19:16232] mca:base:select: Auto-selecting mtl components
[h-19:16232] mca:base:select:(  mtl) Querying component [ofi]
[h-19:16232] mca:base:select:(  mtl) Query of component [ofi] set priority to 10
[h-19:16232] mca:base:select:(  mtl) Querying component [psm]
[h-19:16232] mca:base:select:(  mtl) Query of component [psm] set priority to 100
[h-19:16232] mca:base:select:(  mtl) Selected component [psm]
[h-19:16232] mca: base: close: component ofi closed
[h-19:16232] mca: base: close: unloading component ofi
[h-19:16232] select: initializing mtl component psm
[h-18:04829] mca: base: components_register: registering mtl components
[h-18:04829] mca: base: components_register: found loaded component ofi
[h-18:04829] mca: base: components_register: component ofi register function successful
[h-18:04829] mca: base: components_register: found loaded component psm
[h-18:04829] mca: base: components_register: component psm register function successful
[h-18:04829] mca: base: components_open: opening mtl components
[h-18:04829] mca: base: components_open: found loaded component ofi
[h-18:04829] mca: base: components_open: component ofi open function successful
[h-18:04829] mca: base: components_open: found loaded component psm
[h-18:04829] mca: base: components_open: component psm open function successful
[h-18:04829] mca:base:select: Auto-selecting mtl components
[h-18:04829] mca:base:select:(  mtl) Querying component [ofi]
[h-18:04829] mca:base:select:(  mtl) Query of component [ofi] set priority to 10
[h-18:04829] mca:base:select:(  mtl) Querying component [psm]
[h-18:04829] mca:base:select:(  mtl) Query of component [psm] set priority to 100
[h-18:04829] mca:base:select:(  mtl) Selected component [psm]
[h-18:04829] mca: base: close: component ofi closed
[h-18:04829] mca: base: close: unloading component ofi
[h-18:04829] select: initializing mtl component psm
[h-19:16232] select: init returned success
[h-19:16232] select: component psm selected
[h-18:04829] select: init returned success
[h-18:04829] select: component psm selected
MPI_T_init_thread() ret=0, provided=0
MPI_T_cvar_get_num ret=0, num_cvar=1146
MPI_T_pvar_get_num ret=0, num_pvar=2
MPI_T_init_thread() ret=0, provided=0
MPI_T_cvar_get_num ret=0, num_cvar=1146
MPI_T_pvar_get_num ret=0, num_pvar=2
[h-18:04829] mca: base: close: component psm closed
[h-18:04829] mca: base: close: unloading component psm
[h-19:16232] mca: base: close: component psm closed
[h-19:16232] mca: base: close: unloading component psm

```

**Comment by rhc54** [comment]
FWIW: I reviewed the code and it looks fine. Rolf: are you sure that tarball is current?

**Comment by rolfv** [comment]
This is with an updated master from this morning. Here is what my output looks like.  Looks like maybe a clue in there.
```
rvandevaart@drossetti-ivy4 nv]$ mpirun --mca mtl_base_verbose 100 -np 1 ./simple_tools_test
[drossetti-ivy4.nvidia.com:28422] mca: base: components_register: registering mtl components
[drossetti-ivy4.nvidia.com:28422] mca: base: components_register: found loaded component ofi
[drossetti-ivy4.nvidia.com:28422] mca: base: components_register: component ofi register function successful
[drossetti-ivy4.nvidia.com:28422] mca: base: components_register: found loaded component psm
[drossetti-ivy4.nvidia.com:28422] mca: base: components_register: component psm register function successful
[drossetti-ivy4.nvidia.com:28422] mca: base: components_open: opening mtl components
[drossetti-ivy4.nvidia.com:28422] mca: base: components_open: found loaded component ofi
[drossetti-ivy4.nvidia.com:28422] mca: base: components_open: component ofi open function successful
[drossetti-ivy4.nvidia.com:28422] mca: base: components_open: found loaded component psm
[drossetti-ivy4.nvidia.com:28422] mca: base: close: component psm closed
[drossetti-ivy4.nvidia.com:28422] mca: base: close: unloading component psm
[drossetti-ivy4.nvidia.com:28422] mca:base:select: Auto-selecting mtl components
[drossetti-ivy4.nvidia.com:28422] mca:base:select:(  mtl) Querying component [ofi]
[drossetti-ivy4.nvidia.com:28422] mca:base:select:(  mtl) Query of component [ofi] set priority to 10
[drossetti-ivy4.nvidia.com:28422] mca:base:select:(  mtl) Selected component [ofi]
[drossetti-ivy4.nvidia.com:28422] select: initializing mtl component ofi
[drossetti-ivy4.nvidia.com:28422] ../../../../../ompi/mca/mtl/ofi/mtl_ofi_component.c:194: fi_getinfo failed: No da\
ta available
[drossetti-ivy4.nvidia.com:28422] select: init returned failure for component ofi
[drossetti-ivy4.nvidia.com:28422] select: no component selected
[drossetti-ivy4.nvidia.com:28422] mca: base: close: component ofi closed
[drossetti-ivy4.nvidia.com:28422] mca: base: close: unloading component ofi
[drossetti-ivy4.nvidia.com:28422] mca: base: components_register: registering mtl components
[drossetti-ivy4.nvidia.com:28422] mca: base: components_register: found loaded component ofi
[drossetti-ivy4.nvidia.com:28422] mca: base: components_register: component ofi register function successful
[drossetti-ivy4.nvidia.com:28422] mca: base: components_register: found loaded component psm
[drossetti-ivy4.nvidia.com:28422] mca: base: components_register: component psm register function successful
MPI_T_init_thread() ret=0, provided=0
MPI_T_cvar_get_num ret=0, num_cvar=1213
MPI_T_pvar_get_num ret=0, num_pvar=2
--------------------------------------------------------------------------
mpirun noticed that process rank 0 with PID 0 on node drossetti-ivy4 exited on signal 11 (Segmentation fault).
--------------------------------------------------------------------------
[rvandevaart@drossetti-ivy4 nv]$
```

**Comment by jsquyres** [comment]
FWIW, I'm able to replicate this on today's master when I run on a machine with no PSM hardware.  That may be the key.

**Comment by yburette** [comment]
Thank you. I'm now able to reproduce the error on my system. It is the equivalent of trying to use a non-existing OFI provider:
```--mca mtl ofi --mca mtl_ofi_provider bla```

I'm still not sure what's missing here. When fi_getinfo() fails, init() returns NULL.

Is there a problem with the unloading of the component?
```
[drossetti-ivy4.nvidia.com:28422] select: init returned failure for component ofi
[drossetti-ivy4.nvidia.com:28422] select: no component selected
[drossetti-ivy4.nvidia.com:28422] mca: base: close: component ofi closed
[drossetti-ivy4.nvidia.com:28422] mca: base: close: unloading component ofi
[drossetti-ivy4.nvidia.com:28422] mca: base: components_register: registering mtl components
[drossetti-ivy4.nvidia.com:28422] mca: base: components_register: found loaded component ofi
[drossetti-ivy4.nvidia.com:28422] mca: base: components_register: component ofi register function successful
```

Do I need to "unregister" my string parameter somehow?

**Comment by jsquyres** [comment]
@hjelmn Can you comment on this?  The relevant code is https://github.com/open-mpi/ompi/blob/master/ompi/mca/mtl/ofi/mtl_ofi_component.c#L64-L83

**Comment by hjelmn** [comment]
The string should be getting automatically deregistered when the component is unloaded. Let me verify this is working as intended for this case.

**Comment by hjelmn** [comment]
I see the problem. Working on a fix now.

**Comment by rolfv** [comment]
Just an FYI that this is still failing for me.- March 17, 2015 latest master.

**Comment by hjelmn** [comment]
Should be fixed now.

**Comment by rolfv** [comment]
Well, this test program still fails for me.  I still get a SEGV but this stack track is odd.
```
[rvandevaart@drossetti-ivy4 nv]$ mpirun -np 1 toolbug
MPI_T_init_thread() ret=0, provided=0
MPI_T_cvar_get_num ret=0, num_cvar=1160
MPI_T_pvar_get_num ret=0, num_pvar=2
--------------------------------------------------------------------------
mpirun noticed that process rank 0 with PID 0 on node drossetti-ivy4 exited on signal 11 (Segmentation fault).
--------------------------------------------------------------------------
[rvandevaart@drossetti-ivy4 nv]$ 
```

```
(gdb) where
#0  0x00007fb95fbc41d0 in ?? ()
#1  <signal handler called>
#2  0x00007fb96b204fc0 in ?? ()
#3  0x00007fb972fb78aa in calloc () from /lib64/libc.so.6
#4  0x00007fb9722f373c in mca_base_var_generate_full_name4 (project=0x0, framework=0x1f88978 "vprotocol", component=0x7fb96a0a78b8 "pessimist", variable=0x0, 
    full_name=0x7fff62b56430) at ../../../../opal/mca/base/mca_base_var.c:165
#5  0x00007fb9722fd17b in group_find (project_name=0x0, framework_name=0x1f88978 "vprotocol", component_name=0x7fb96a0a78b8 "pessimist", invalidok=false)
    at ../../../../opal/mca/base/mca_base_var_group.c:160
#6  0x00007fb9722fdccd in mca_base_var_group_find (project_name=0x0, framework_name=0x1f88978 "vprotocol", component_name=0x7fb96a0a78b8 "pessimist")
    at ../../../../opal/mca/base/mca_base_var_group.c:351
#7  0x00007fb9722f1439 in ri_destructor (obj=0x1f88930) at ../../../../opal/mca/base/mca_base_component_repository.c:360
#8  0x00007fb9722f068d in opal_obj_run_destructors (object=0x1f88930) at ../../../../opal/class/opal_object.h:446
#9  0x00007fb9722f10c2 in mca_base_component_repository_finalize () at ../../../../opal/mca/base/mca_base_component_repository.c:264
#10 0x00007fb9722ed39d in mca_base_close () at ../../../../opal/mca/base/mca_base_close.c:45
#11 0x00007fb9722bd8c2 in opal_finalize () at ../../opal/runtime/opal_finalize.c:172
#12 0x00007fb9725d5440 in orte_finalize () at ../../orte/runtime/orte_finalize.c:79
#13 0x00007fb9735419e0 in ompi_mpi_finalize () at ../../ompi/runtime/ompi_mpi_finalize.c:432
#14 0x00007fb97356a5dd in PMPI_Finalize () at pfinalize.c:46
#15 0x0000000000400d10 in main (argc=1, argv=0x7fff62b56738) at toolbug.c:13
(gdb) up 2
#2  0x00007fb96b204fc0 in ?? ()
(gdb) up
#3  0x00007fb972fb78aa in calloc () from /lib64/libc.so.6
(gdb) up
#4  0x00007fb9722f373c in mca_base_var_generate_full_name4 (project=0x0, framework=0x1f88978 "vprotocol", component=0x7fb96a0a78b8 "pessimist", variable=0x0, 
    full_name=0x7fff62b56430) at ../../../../opal/mca/base/mca_base_var.c:165
165	    name = calloc (1, len);
(gdb) print len
$1 = 20
(gdb) print name
$2 = 0x1f6b6a0 "t_size"
(gdb) 
```

**Comment by rolfv** [comment]
I also realized I only see this when the openib BTL is in the list of BTLs.

**Comment by hjelmn** [comment]
Hmm. That might be why i could no longer reproduce. I was running without openib. Will dig deeper.

**Comment by hjelmn** [comment]
I might have an idea what is going wrong. Open MPI sets up classes lazily as we call constructors. Now, if an object from a particular class were to be destructed *after* its component is dlclose'd the destructor function pointer would point to garbage and we might get weird stack traces, crashes, etc.

**Comment by jsquyres** [comment]
@hjelmn Are you implying that there's something in openib that is being destructed after it is dlclosed?

**Comment by rolfv** [comment]
One other observation.  My nightly tests are all passing.  I realized the difference is whether the host I am running on is remote or not.  For example:
```
[rvandevaart@drossetti-ivy0 nv]$ mpirun -np 1 -host drossetti-ivy0 toolbug
MPI_T_init_thread() ret=0, provided=0
MPI_T_cvar_get_num ret=0, num_cvar=1221
MPI_T_pvar_get_num ret=0, num_pvar=2
--------------------------------------------------------------------------
mpirun noticed that process rank 0 with PID 0 on node drossetti-ivy0 exited on signal 11 (Segmentation fa\
ult).
--------------------------------------------------------------------------
[rvandevaart@drossetti-ivy0 nv]$ mpirun -np 1 -host drossetti-ivy4 toolbug
MPI_T_init_thread() ret=0, provided=0
MPI_T_cvar_get_num ret=0, num_cvar=1221
MPI_T_pvar_get_num ret=0, num_pvar=2
[rvandevaart@drossetti-ivy0 nv]$ echo $?
0
[rvandevaart@drossetti-ivy0 nv]$
```

**Comment by hjelmn** [comment]
Could you try disabling oob/ud with -mca oob ^ud?

**Comment by hjelmn** [comment]
@jsquyres I don't know. Just trying to think of possible reasons for the bizarre stack trace.

On a side-note. Think about this possibility... MPI_T causes component x to be loaded (dlopened). It creates an instance of class y causing class y to be initialized in the opal base. The user then calls MPI_T_Finalize causing component x to be unloaded (dlclosed). MPI_Init then loads component x which then tries to create an instance of class y. What will happen? Bad things...

We may need to leave all loaded components dlopened until the end execution to fix that problem. I may re-open the discussion about using an __attribute__((destructor)) function in open to clean up the component repository and the class system. I know not all compilers/platforms support it but the ones we care about do (linux, OSX).

**Comment by jsquyres** [comment]
@hjelmn What if we never dlclose anything until at least MPI_Finalize?  And if MPI_Finalize is invoked while MPI_T is still initialized, we can defer the dlclosing until MPI_T_Finalize is invokes.

Specificially, in a sequence like this:

1. MPI_T_Init
1. MPI_T_Finalize -- don't actually finalize anything here
1. Repeat the first 2 steps a few times
1. MPI_Init
1. MPI_T_init
1. MPI_Finalize -- don't actually finalize anything here because MPI_T is still intialized
1. MPI_T_finalize -- go ahead and finalize/close everything
1. MPI_T_init -- this could be the problem case.  Can we have MPI_T effectively neutered in this case?  I.e., it's "initialized", but it won't be able to do very much...?

**Comment by jsquyres** [comment]
@rolfv Just curious: does the patch from #392 find the errant MCA var?

**Comment by rolfv** [comment]
@jsquyres I just tested with patch from #392.  The code in the patch is not triggered and I still get the same crash.  However, I also added some opal_output() into the var_destructor() function to make sure I was going through the new code you added.. However, I see no output.  So, I am not even sure if the var_destructor() function is being called.  I must be missing something.

**Comment by rolfv** [comment]
OK, figured out that opal_output() was not working for me.  But printf does.  So, in conclusion, the patch is not triggered so the SEGV I am seeing now must be a different issue.
