### ISSUE TITLE
pmix3x master build failed

### ISSUE THREAD

**Issue by thananon** [open-mpi/ompi#5299]
Hi, I just update to current master and I failed to build with this error

```
make[5]: Entering directory `/nfs/site/disks/fabric_work/tpatinya/ompi/opal/mca/pmix/pmix3x/pmix/src/mca/pnet/opa'
  CC       pnet_opa.lo
In file included from /usr/include/opamgt/iba/stl_sa_types.h:68:0,
                 from /usr/include/opamgt/iba/ib_sd.h:54,
                 from /usr/include/opamgt/iba/stl_sd.h:34,
                 from /usr/include/opamgt/opamgt_sa.h:41,
                 from pnet_opa.c:31:
/usr/include/opamgt/iba/ib_sa_records.h:40:21: fatal error: iba/vpi.h: No such file or directory
```
OS: RHEL 7
Compiler: GCC 4.8
CLA:  

`./configure --prefix=${HOME}/opt/mpi --disable-debug --with-platform=optimized --enable-mpirun-prefix-by-default --enable-picky --with-libfabric=${HOME}/opt/libfabric`

Also on unrelated not, there is now a lot of -Wunused messages I have never seen before.
```
nfs/site/disks/fabric_work/tpatinya/ompi/opal/class/opal_value_array.h:84:19: warning: 'opal_value_array_reserve' defined but not used [-Wunused-function]
 static inline int opal_value_array_reserve(opal_value_array_t* array, size_t size)
                   ^
/nfs/site/disks/fabric_work/tpatinya/ompi/opal/threads/mutex_unix.h:174:19: warning: 'opal_mutex_atomic_trylock' defined but not used [-Wunused-function]
 static inline int opal_mutex_atomic_trylock(opal_mutex_t *m)
                   ^
/nfs/site/disks/fabric_work/tpatinya/ompi/opal/class/opal_value_array.h:107:22: warning: 'opal_value_array_get_size' defined but not used [-Wunused-function]
 static inline size_t opal_value_array_get_size(opal_value_array_t* array)
                      ^
/nfs/site/disks/fabric_work/tpatinya/ompi/opal/threads/mutex_unix.h:179:20: warning: 'opal_mutex_atomic_lock' defined but not used [-Wunused-function]
 static inline void opal_mutex_atomic_lock(opal_mutex_t *m)
                    ^
/nfs/site/disks/fabric_work/tpatinya/ompi/opal/class/opal_value_array.h:160:21: warning: 'opal_value_array_get_item' defined but not used [-Wunused-function]
 static inline void* opal_value_array_get_item(opal_value_array_t *array, size_t item_index)
                     ^
/nfs/site/disks/fabric_work/tpatinya/ompi/opal/threads/mutex_unix.h:184:20: warning: 'opal_mutex_atomic_unlock' defined but not used [-Wunused-function]
 static inline void opal_mutex_atomic_unlock(opal_mutex_t *m)
                    ^
/nfs/site/disks/fabric_work/tpatinya/ompi/opal/class/opal_value_array.h:225:19: warning: 'opal_value_array_append_item' defined but not used [-Wunused-function]
 static inline int opal_value_array_append_item(opal_value_array_t *array, const void *item)
                   ^
/nfs/site/disks/fabric_work/tpatinya/ompi/opal/class/opal_value_array.h:243:19: warning: 'opal_value_array_remove_item' defined but not used [-Wunused-function]
 static inline int opal_value_array_remove_item(opal_value_array_t *array, size_t item_index)
```
@rhc54 Any drastic change in the code lately?

**Comment by rhc54** [comment]
The warnings are fixed by a commit from @ggouaillardet this morning - there was a problem in opal_setup_cc.m4 that caused the ```inline``` keyword to be defined to nothing.

For the other error - it looks like we need a little more configure checking. We look for opamgt and found it on your system, but your system is missing the IB support libraries for opamgt to work. For now, just configure --without-opamgt

**Comment by thananon** [comment]
Thank you Ralph.

**Comment by thananon** [comment]
It seems that I have @ggouaillardet patch in the current master head but still get the warnings. I'm not sure if they are related or did you mean this commit?

```
commit d44e0409c7e90bec49f241be13f325c762376ae4
Merge: f301cab c9d3c81
Author: Gilles Gouaillardet <ggouaillardet@users.noreply.github.com>
Date:   Tue Jun 19 13:42:28 2018 +0900

    Merge pull request #4822 from ggouaillardet/topic/opal_setup_cc

    configury: define C11 macros once

commit c9d3c81cbf97df97ebe0de8e4761e8c7a9278f48
Author: Gilles Gouaillardet <gilles@rist.or.jp>
Date:   Fri Jun 15 10:36:17 2018 +0900

    configury: define C11 macros once

    Revamp OPAL_PROG_CC_C11 macro in order to define macros only once.
    Otherwise, macros get redefined during the configure process and
    issue a bunch of warning in config.log. That would also cause
    Open MPI fail to build if compiled with "-Werror"

    Refs. open-mpi/ompi#5190

    Signed-off-by: Gilles Gouaillardet <gilles@rist.or.jp>
```

**Comment by rhc54** [comment]
That is the one that fixed the problem for us - sounds like you may be hitting the same problem but via a different mechanism. Not sure I can offer any advice - for whatever reason, you wind up with ```inline``` being defined out. You can get around it for now by just removing that --enable-picky option.

**Comment by rhc54** [comment]
FWIW: I committed a fix for the opamgt configure logic.

**Comment by thananon** [comment]
Thank you guys. Closing this.

**Comment by ggouaillardet** [comment]
I added my fixes to https://github.com/pmix/pmix/pull/760 (updates to PMIx v3.0 branch).

So we have two options
 - wait for this to get merged, and update the embedded PMIx (v3.0 branch) in Open MPI
 - directly update the embedded PMIx (master branch) and move the component to `pmix4x`

@rhc54 any suggestion ?

**Comment by ggouaillardet** [comment]
@thananon just to be clear, the commit you reference only fixes OPAL.
The same error was backported into PMIx and then landed into the embedded PMIx,
and the fix has yet to land into the embedded PMIx.

**Comment by rhc54** [comment]
I'm going to bring it all around tonight - thanks @ggouaillardet !
