### ISSUE TITLE
Problems with keepalive support

### ISSUE THREAD

**Issue by jsquyres** [open-mpi/ompi#592]
Per discussion on the OMPI call today, I tried the following keepalive experiment on master and v1.8:

* Not in a SLURM allocation
* Used a trivial "mpi_sleep" program that I wrote:

```c
#include <stdio.h>
#include <stdlib.h>
#include <sys/types.h>
#include <unistd.h>
#include <mpi.h>
#include <time.h>

int main()
{
    int i;
    pid_t pid = getpid();

    char hostname[MPI_MAX_PROCESSOR_NAME];
    int len = MPI_MAX_PROCESSOR_NAME;

    MPI_Init(NULL, NULL);
    MPI_Get_processor_name(hostname, &len);

    for (i = 0; i < 10000; ++i) {
        time_t t;
        char *s;
        t = time(NULL);
        s = ctime(&t);
        s[24] = '\0';
        printf("%s: PID %d on host %s sleeping...\n",
               s, pid, hostname);
        sleep(2);
    }
    MPI_Finalize();
    return 0;
}
```

* `mpirun --host a,b -np 2 mpi_sleep` (this is using the connectionless usnic transport between servers).
* mpirun is running on the cluster head node (which is neither `a` nor `b`)
* I let the job run for a few iterations.
* I then powered off node `b`.
* As expected, the output continued from node a.

However, the job *did not die* after several minutes (I did not keep track of how long, but it was several minutes).  So I checked the output of `ompi_info --all --parsable | grep keep | grep value:`.  I saw that our keepalive time is 10, but the interval is 60 (and the probes is 3).

**FIRST PROBLEM:** I'm not sure if it makes sense to have the (interval*probes) be longer than the keepalive time.  I think we need to change the default values of these MCA params.

So I re-ran the same test, but with:

* `mpirun --host a,b --mca oob_tcp_keepalive_intvl 2  -np 2 mpi_sleep`
* Just like above, I let it run for several iterations (beyond the keepalive time of 10 seconds), and then I powered off node `b`.
* As expected, the output from `a` continued for a while.
* And then, also as expected, then the output `a` stopped.

**SECOND PROBLEM:** ...but mpirun did not quit.

I re-ran with `--mca oob_base_verbose 100` to see if it gave more insight, and it did.  After (timeout + interval * probes), I see ("ivy01" is node `a`):

```
[ivy01:06135] [[15802,0],1] USOCK SHUTDOWN
[ivy01:06135] [[15802,0],1] TCP SHUTDOWN
[ivy01:06135] [[15802,0],1] RELEASING PEER OBJ [[15802,0],2]
[ivy01:06135] [[15802,0],1] RELEASING PEER OBJ [[15802,0],0]
[ivy01:06135] [[15802,0],1] CLOSING SOCKET 11
[ivy01:06135] [[15802,0],1] oob:ud:component_close entering
[ivy01:06135] mca: base: close: component ud closed
[ivy01:06135] mca: base: close: unloading component ud
[ivy01:06135] mca: base: close: component tcp closed
[ivy01:06135] mca: base: close: unloading component tcp
[ivy01:06135] mca: base: close: component usock closed
[ivy01:06135] mca: base: close: unloading component usock
```

So it looks like ORTE detected the keepalive failure, and *tried* to shut everything down and quit, but failed to do so.  Attaching a debugging to mpirun, I see that it's stuck in the following orterun.c loop (which is pretty much expected):

```c
    /* loop the event lib until an exit event is detected */
    while (orte_event_base_active) {
        opal_event_loop(orte_event_base, OPAL_EVLOOP_ONCE);
    }
```

Digging a little deeper, it looks like the `ssh` out to node `b` is still active ("ivy02" is `b`) -- i.e., the ssh to `b` hasn't timed out and died yet:

```shell
$ ps -eadf | grep orted
jsquyres 12043 12040  0 18:17 pts/17   00:00:00 /usr/bin/ssh -x ivy02     PATH=/home/jsquyres/bogus/bin:$PATH ; export PATH ; LD_LIBRARY_PATH=/home/jsquyres/bogus/lib:$LD_LIBRARY_PATH ; export LD_LIBRARY_PATH ; DYLD_LIBRARY_PATH=/home/jsquyres/bogus/lib:$DYLD_LIBRARY_PATH ; export DYLD_LIBRARY_PATH ;   /home/jsquyres/bogus/bin/orted --hnp-topo-sig 2N:2S:2L3:16L2:16L1:16C:32H:x86_64 -mca ess "env" -mca orte_ess_jobid "2114846720" -mca orte_ess_vpid 2 -mca orte_ess_num_procs "3" -mca orte_hnp_uri "2114846720.0;usock;tcp://10.0.8.254,10.193.184.48,10.193.184.49,10.10.0.254,10.2.0.254,10.3.0.254,10.3.0.252,10.50.0.254:49786" --tree-spawn --mca oob_base_verbose "100" --mca oob_tcp_keepalive_intvl "2" -mca plm "rsh" --tree-spawn
```

Is the presence of this ssh keeping mpirun around?

I read ssh_config(5), and it looks like ssh defaults to setting TCPKeepAlive to "yes", meaning that it enables TCP keepalive.  But we have no idea what its timeout/interval/probes values are.  Apparently they're pretty long.

However, I see ssh's ServerAliveInterval option -- I hacked plm_rsh_module.c to add "-o" and "ServerAliveInterval 5" to the ssh command line (couldn't use `plm_rsh_args` because it splits the "ServerAliveInterval 5" into 2 tokens).  In this case, ssh *does* recognize that the remote side has died and it quits -- apparently emitting the following message to stderr:

```
Timeout, server not responding.
```

**THIRD PROBLEM:** However, mpirun still does not quit.  :-(

Sooo... I'm not sure if we need to pass this option to ssh or not (i.e., if ORTE detecting the dead socket will be sufficient for ORTE to be able to shut everything down, including any children ssh's that are still hanging around).

I'm not sure what mpirun is waiting for -- @rhc54 -- can you have a look into this?

**Comment by jsquyres** [comment]
I forgot to mention -- the behavior is essentially the same on the v1.8 branch.

**Comment by bosilca** [comment]
I am not sure that the ssh connection was still supposed to be around? I have a recollection that once we started the daemon it forks and the ssh connections returns. So I would guess that the orterun issue is independent on the ssh session being active.

As a side note: I checked on our fault tolerant version (based on 1.6) and the ssh connections disappear once the orte daemons are up.

**Comment by rhc54** [comment]
It sticks around if one sets the debug options or asks for --leave-session-attached. I suspect Jeff is working in debug mode and so the connection remains active.

**Comment by jsquyres** [comment]
I did a debug build, but I did not specify `--leave-session-attached`.

Either way, it's apparently not (only) the ssh session sticking around that is causing mpirun to not die.  Is there just a missing `orte_errmgr.abort()` somewhere, perchance?

**Comment by rhc54** [comment]
I'll take a look at it

**Comment by rhc54** [comment]
@jsquyres I reviewed the code and don't see an obvious error. I did see a code path that would result in this behavior, but you shouldn't have gone down it given your reported setup and cmd.

Can you add "--mca errmgr_base_verbose 10 --mca oob_base_verbose 100" to the cmd line and send me the entire output?

**Comment by jsquyres** [comment]
Done -- full output is in this gist:

    https://gist.github.com/jsquyres/3209c46f07cdb34a6f76

This was across 2 machines (ivy01,ivy02), not in a slurm job, without `--leave-session-attached`, and with the errmgr and oob verbose output.

The job hung at the bottom of the gist output:

* ivy02 was powered down
* all jsquyres processes on ivy01 were dead
* On the head node (where mpirun is running), these are the only processes left (the ssh to ivy01 is dead but not yet reaped, the ssh to ivy02 hasn't died/timed out yet):

```
jsquyres 25277 11240 82 07:35 pts/3    00:03:48 mpirun --mca oob_tcp_keepalive_time 10 --mca errmgr_base_verbose 10 --mca oob_base_verbose 100 --host ivy01,ivy02 --mca btl usnic,sm,self mpi_sleep
jsquyres 25279 25277  0 07:35 pts/3    00:00:00 [ssh] <defunct>
jsquyres 25280 25277  0 07:35 pts/3    00:00:00 /usr/bin/ssh -x ivy02     PATH=/home/jsquyres/bogus/bin:$PATH ; export PATH ; LD_LIBRARY_PATH=/home/jsquyres/bogus/lib:$LD_LIBRARY_PATH ; export LD_LIBRARY_PATH ; DYLD_LIBRARY_PATH=/home/jsquyres/bogus/lib:$DYLD_LIBRARY_PATH ; export DYLD_LIBRARY_PATH ;   /home/jsquyres/bogus/bin/orted --hnp-topo-sig 2N:2S:2L3:16L2:16L1:16C:32H:x86_64 -mca ess "env" -mca orte_ess_jobid "867893248" -mca orte_ess_vpid 2 -mca orte_ess_num_procs "3" -mca orte_hnp_uri "867893248.0;usock;tcp://10.0.8.254,10.193.184.48,10.193.184.49,10.10.0.254,10.2.0.254,10.3.0.254,10.3.0.252,10.50.0.254:45024" --tree-spawn --mca oob_tcp_keepalive_time "10" --mca errmgr_base_verbose "10" --mca oob_base_verbose "100" --mca btl "usnic,sm,self" -mca plm "rsh" --tree-spawn
```

**Comment by rhc54** [comment]
@jsquyres I think I have the rather trivial fix required here - can you please apply and try the following:

```c
diff --git a/orte/mca/oob/tcp/oob_tcp_sendrecv.c b/orte/mca/oob/tcp/oob_tcp_sendrecv.c
index f75827a..35e72a7 100644
--- a/orte/mca/oob/tcp/oob_tcp_sendrecv.c
+++ b/orte/mca/oob/tcp/oob_tcp_sendrecv.c
@@ -431,10 +431,6 @@ void mca_oob_tcp_recv_handler(int sd, short flags, void *cbdata)
     bool timing_same_as_hdr = false;
 #endif
 
-    if (orte_abnormal_term_ordered) {
-        return;
-    }
-
     opal_output_verbose(OOB_TCP_DEBUG_CONNECT, orte_oob_base_framework.framework_output,
                         "%s:tcp:recv:handler called for peer %s",
                         ORTE_NAME_PRINT(ORTE_PROC_MY_NAME),
```

**Comment by jsquyres** [comment]
Sweet!  It now [mostly] works.  The only "glitch" is that it exits without any kind of error message, and mpirun's exit status is 0:

```
$ mpirun --mca oob_tcp_keepalive_time 10 --mca errmgr_base_verbose 00 --mca oob_base_verbose 00 --host ivy01,ivy04 --mca btl usnic,sm,self ~/mpi/mpi_sleep
Fri May 22 13:01:29 2015: PID 22861 on host ivy01 sleeping...
Fri May 22 13:01:29 2015: PID 22655 on host ivy04 sleeping...
Fri May 22 13:01:31 2015: PID 22861 on host ivy01 sleeping...
Fri May 22 13:01:31 2015: PID 22655 on host ivy04 sleeping...
Fri May 22 13:01:33 2015: PID 22861 on host ivy01 sleeping...
Fri May 22 13:01:33 2015: PID 22655 on host ivy04 sleeping...
Fri May 22 13:01:35 2015: PID 22861 on host ivy01 sleeping...
Fri May 22 13:01:35 2015: PID 22655 on host ivy04 sleeping...
Fri May 22 13:01:37 2015: PID 22861 on host ivy01 sleeping...
Fri May 22 13:01:37 2015: PID 22655 on host ivy04 sleeping...
Fri May 22 13:01:39 2015: PID 22861 on host ivy01 sleeping...
Fri May 22 13:01:39 2015: PID 22655 on host ivy04 sleeping...
[... Jeff powers off ivy04 in a different window ...]
Fri May 22 13:01:41 2015: PID 22861 on host ivy01 sleeping...
Fri May 22 13:01:43 2015: PID 22861 on host ivy01 sleeping...
Fri May 22 13:01:45 2015: PID 22861 on host ivy01 sleeping...
Fri May 22 13:01:47 2015: PID 22861 on host ivy01 sleeping...
Fri May 22 13:01:49 2015: PID 22861 on host ivy01 sleeping...
Fri May 22 13:01:51 2015: PID 22861 on host ivy01 sleeping...
Fri May 22 13:01:53 2015: PID 22861 on host ivy01 sleeping...
Fri May 22 13:01:55 2015: PID 22861 on host ivy01 sleeping...
Fri May 22 13:01:57 2015: PID 22861 on host ivy01 sleeping...
Fri May 22 13:01:59 2015: PID 22861 on host ivy01 sleeping...
Fri May 22 13:02:01 2015: PID 22861 on host ivy01 sleeping...
Fri May 22 13:02:03 2015: PID 22861 on host ivy01 sleeping...
[1:02] savbu-usnic-a:~/g/o/examples (master●)
$ echo $status
0
```

**Comment by rhc54** [comment]
hmmm...okay, i can easily fix that one. Will do so and set it up.

Thx!

**Comment by rhc54** [comment]
Fixed and committed to master

**Comment by tgpfeiffer** [comment]
I am not sure whether this is related to "keepalive support" or not, but I still see that behavior on 2.1.1, and also 2.1.2, as described here: https://mail-archive.com/users@lists.open-mpi.org/msg31592.html
Has the patch from above(https://github.com/open-mpi/ompi/issues/592#issuecomment-104737547) made it to the main source code? Looking at https://github.com/open-mpi/ompi/blob/v2.1.2/orte/mca/oob/tcp/oob_tcp_sendrecv.c#L414 it looks as if it has not.

For me, if `orted` dies, then on rank 0 both `python` and both `ssh` instances become defunct, on the other two ranks only the `python` instance. However, on 3.0.0 it seems as if the process exits correctly after emitting the "lost communication" message.

**Comment by rhc54** [comment]
Hmmm...I see the code went into master, which is where the code referenced here was targeted. However, I agree that I don't see where it was PR'd to the release branches.

@jsquyres did you forget to move this across?
