### ISSUE TITLE
Warnings in variable arg lists

### ISSUE THREAD

**Issue by rhc54** [open-mpi/ompi#6052]
Seeing these consistently lately on master when building on Mac OSX (using default Apple LLVM version 10.0.0 (clang-1000.11.45.5) compiler):
```shell
util/os_path.c:43:18: warning: passing an object that undergoes default argument promotion to 'va_start' has undefined
      behavior [-Wvarargs]
    va_start(ap, relative);
                 ^
util/os_path.c:37:25: note: parameter of type 'bool' is declared here
char *pmix_os_path(bool relative, ...)
                        ^
util/os_path.c:90:18: warning: passing an object that undergoes default argument promotion to 'va_start' has undefined
      behavior [-Wvarargs]
    va_start(ap, relative);
                 ^
util/os_path.c:37:25: note: parameter of type 'bool' is declared here
char *pmix_os_path(bool relative, ...)
                        ^
2 warnings generated.
util/show_help.c:332:23: warning: passing an object that undergoes default argument promotion to 'va_start' has undefined
      behavior [-Wvarargs]
    va_start(arglist, want_error_handler);
                      ^
util/show_help.c:327:34: note: parameter of type 'bool' is declared here
                            bool want_error_handler, ...)
                                 ^
util/show_help.c:365:23: warning: passing an object that undergoes default argument promotion to 'va_start' has undefined
      behavior [-Wvarargs]
    va_start(arglist, want_error_header);
                      ^
util/show_help.c:359:41: note: parameter of type 'bool' is declared here
                                   bool want_error_header, ...)
```

**Comment by bosilca** [comment]
This was supposedly fixed by @jsquyres in 3970b061340.

**Comment by jsquyres** [comment]
I didn't fix anything in pmix -- but I did fix this kind of stuff in OMPI.

I think that the `util/os_path.c` and `util/show_help.c` in the description above is in PMIX, because the line number doesn't match up with `opal/util/[os_path.c|show_help.c]` on master...?

**Comment by rhc54** [comment]
Sigh - will fix upstream then.
