### ISSUE TITLE
MPI Generalized requests failing on 4.1.0

### ISSUE THREAD

**Issue by amckinstry** [open-mpi/ompi#8402]
This is on Debian unstable, with OpenMPI 4.1.0 in MPI4PY (3.0.3) test suite.

The errors we're seeing are here:
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=979480

The tests work with openmpi 4.0.5.

In both cases the /etc/openmpi/openmpi-mca-params.conf has:
```
btl_base_warn_component_unused=0
# Avoid openib an in case applications use fork: see https://github.com/ofiwg/libfabric/issues/6332
# If you wish to use openib and know your application is safe, remove the following:
# Similarly for UCX: https://github.com/open-mpi/ompi/issues/8367
btl = ^uct,openib,ofi
pml = ^ucx
osc = ^ucx,pt2pt
```
to allow testing on single node systems (This is with oversubscription enabled).

Failed case uses pmix 4.0.0, working case uses 3.2.2

**Comment by rhc54** [comment]
Just to be clear: are you saying the OMPI v4.1.0 passes these tests if configured with PMIx v3.2.2, but fails if configured with PMIx v4.0.0? There as a bug in generalized requests that has been fixed on the branch, but that had nothing to do with PMIx (AFAIK).

**Comment by amckinstry** [comment]
A quick test shows trying 4.1.0 with pmix 3.2.2 doesn't fix it

**Comment by amckinstry** [comment]
So something has changed in 4.0.5 -> 4.1.0 (or our related config)

**Comment by jsquyres** [comment]
This was fixed in #8340.

**Comment by jsquyres** [comment]
To clarify: this was reported in #8340 and fixed in the v4.1.x branch in #8348.

**Comment by amckinstry** [comment]
This solves the issue for us.

**Comment by jsquyres** [comment]
@amckinstry Excellent. FYI: we only have one or two more things before we plan to roll a v4.1.1rc.  Should be "Real Soon Now".
