### ISSUE TITLE
darray type incorrectly created or interpreted in mpi_alltoallw

### ISSUE THREAD

**Issue by dmt4** [open-mpi/ompi#965]
Instead of the respective pieces corresponding to the specific darray type, all processes receive the same darray. I've tried to specialise a general routine to a small example working with 2 processes only. Here is a test code: 
https://gist.github.com/anonymous/60de0ae4f52f15b89dae

**Comment by bosilca** [comment]
This test successfully pass with open-mpi/ompi@1cac060 using the basic collective module. Can you check to see what collective function is used in your run.

However, from a datatype perspective the 2 datatypes created by the darray calls look correct.

Datatype 0x7fad99d3faf0[Dup ] id 73 size 4 align 4 opal_id 0 length 4 used 1
true_lb 0 true_ub 4 (true_extent 4) lb 0 ub 8 (extent 8)
nbElems 1 loops 0 flags 114 (committed contiguous )-cC----GD--[---][---]
   contain OPAL_FLOAT4
--C---P-D--[---][---]    OPAL_FLOAT4 count 1 disp 0x0 (0) extent 4 (size 4)
-------G---[---][---]  OPAL_END_LOOP prev 1 elements first elem displacement 0 size of data 4
Optimized description
-cC---P-DB-[---][---]    OPAL_FLOAT4 count 1 disp 0x0 (0) extent 4 (size 4)
-------G---[---][---]  OPAL_END_LOOP prev 1 elements first elem displacement 0 size of data 4

Datatype 0x7fad99d3fd60[Dup ] id 73 size 4 align 4 opal_id 0 length 4 used 1
true_lb 4 true_ub 8 (true_extent 4) lb 4 ub 12 (extent 8)
nbElems 1 loops 0 flags 114 (committed contiguous )-cC----GD--[---][---]
   contain OPAL_FLOAT4
--C---P-D--[---][---]    OPAL_FLOAT4 count 1 disp 0x0 (0) extent 4 (size 4)
-------G---[---][---]  OPAL_END_LOOP prev 1 elements first elem displacement 0 size of data 4
Optimized description
-cC---P-DB-[---][---]    OPAL_FLOAT4 count 1 disp 0x0 (0) extent 4 (size 4)
-------G---[---][---]  OPAL_END_LOOP prev 1 elements first elem displacement 0 size of data 4

**Comment by dmt4** [comment]
Hi, how do i check which collective is being used? I've looked in ompi_info -a and coll_tuned_alltoall_algorithm and coll_tuned_alltoallv_algorithm had default value 0/ignore. I didn't see any alltoallw though.

**Comment by dmt4** [comment]
That commit you quoted does indeed work for me too, compiled it under the same circumstances as the  1.10.0 release which fails.

**Comment by bosilca** [comment]
I looked at the differences between v1.10 and  open-mpi/ompi@1cac060 with regard to datatype and collectives, and the differences are minor.

**Comment by dmt4** [comment]
Asked someone else to try with his compilation and also got a fail with
1.10.0. If could test it would be great.

**Comment by dmt4** [comment]
Tried 1.10.1rc1 just now and the bug is still there. I hope the fix can make it in 1.10.1

**Comment by rhc54** [comment]
That can't be the right sha - when I click on it, it just points to a commit that changes an AC output to go to a log file. Can you correct the reference?

**Comment by dmt4** [comment]
I wouldn't most and too much bisecting it to find out, but looking how
there are separate repos for the releases and development I'm not sure
where to start. What is the mapping between the 2?

**Comment by bosilca** [comment]
@rhc54 it is the right sha for the discussion going on here. Read the entire flow.

**Comment by rhc54** [comment]
When I click on that link (open-mpi/ompi@1cac060), I get this changeset:

```c
         if test -d "${patch_dir}"; then
             if test ! -f "${patch_done}"; then
 
-                AC_MSG_NOTICE([Checking patches from ${patch_dir}/ directory ])
+                OPAL_LOG_MSG([Checking patches from ${patch_dir}/ directory ])
                 for one_patch in $patch_dir/*.patch ; do
 
                     AC_MSG_CHECKING([patch: $one_patch for errors ])
@@ -129,7 +129,7 @@ AC_DEFUN([OPAL_LOAD_PLATFORM], [
 
 
                 for one_patch in $patch_dir/*.patch ; do
-                    AC_MSG_NOTICE([Applying patch ${one_patch}])
+                    OPAL_LOG_MSG([Applying patch ${one_patch}])
                     patch -d ${srcdir} -p1 -t -s < ${one_patch}
                     if test "$?" != "0"; then
                         AC_MSG_ERROR([Failed to apply patch ${one_patch}])
@@ -161,7 +161,7 @@ AC_DEFUN([OPAL_LOAD_PLATFORM], [
                 AC_MSG_WARN([Platform patches already applied, skipping. ${patch_done} can be removed to re-apply ])
             fi
         else
-            AC_MSG_NOTICE([No platform patches in ${patch_dir}])
+            OPAL_LOG_MSG([No platform patches in ${patch_dir}])
         fi
 
```

Are you telling me that changing those AC messages to an opal_log_msg is enough to fix this problem?

**Comment by rhc54** [comment]
I finally figured out what you are trying to do with that link - an unfortunate use of the link. I was looking for the changeset being referenced as the two branches are clearly unrelated when it comes to a sha, and the provided link made no sense in that context.

If you can identify the missing commit in the immediate future, and if it is small, then we might be able to get it into 1.10.1 as @dmt4 has requested. Otherwise, it will have to wait for 1.10.2.

**Comment by ggouaillardet** [comment]
```git bisect``` reports the faulty commit is open-mpi/ompi-release@a226691179b9ac560a5e999538a28c5ce0b420c7

what ```git bisect``` does not tell is that this commit was (partially) fixed by open-mpi/ompi-release@2f0f519af954df5f40922581b7e759aa5a50a580 and that the last fix is open-mpi/ompi@da83b084f506ea3c34ebe9da3c6dd6f44e2537a8 which has been back ported to v2.x but __not__ to v1.8 nor v1.10 (and btw, v1.8 is no more updated)

i ran zero non-regression tests
@bosilca can you please double check this and PR open-mpi/ompi@da83b084f506ea3c34ebe9da3c6dd6f44e2537a8 for the v1.10 branch if appropriate ?

**Comment by ggouaillardet** [comment]
open-mpi/ompi@da83b084f506ea3c34ebe9da3c6dd6f44e2537a8 was ___no__t back ported to v2.x strictly speaking ... it was already in master when v2.x branch was created

**Comment by ggouaillardet** [comment]
i added the test case to the ibm test suite in open-mpi/ompi-tests@b3d5a47471117442b471c359695a634598607c01

**Comment by dmt4** [comment]
Is this ompi-tests link above private or erroneous?

**Comment by ggouaillardet** [comment]
This is a private repository ...

**Comment by dmt4** [comment]
About open-mpi/ompi-release@2f0f519 and open-mpi/ompi@da83b08 (not) being backported to v1.8. 1.8.4 certainly passes the test and 1.8.8 is broken, I haven't tried anything in between.

**Comment by jsquyres** [comment]
@bosilca @ggouaillardet So are we missing open-mpi/ompi@da83b08 in v1.10.1?  Can someone create a PR for this ASAP?

**Comment by bosilca** [comment]
We are missing a part of open-mpi/ompi@a226691 and open-mpi/ompi@da83b08. I have a patch, I have to test it through the test @ggouaillardet attached to this ticket.

**Comment by bosilca** [comment]
This issue is resolved by https://github.com/open-mpi/ompi-release/pull/639.

**Comment by jsquyres** [comment]
Closed via open-mpi/ompi-release#639

**Comment by dmt4** [comment]
Hi I'm sorry to reopen this but it looks like there is still an issue in cases where there are more than 1 blocks created. Here is the test code:

https://gist.github.com/dmt4/814192affc23f499706b

The previous example was 1x2 matrix over 1x2 process array with block size of 1x1. 1.10.1rc2 fixes this and related example of 1x4 matrix over 1x2 process array with block size of 1x2 works too. Both these are similar in the sense that they deal with 1 block/dimension. If this changes to, say 2, as in the following:  1x4 matrix over 1x2 process array with block size of 1x1 yielding 1x2 blocks in each dimension respectively, then 1.10.1rc2 fails.

**Comment by jsquyres** [comment]
DOH!

@bosilca I'm sorry to push, but how fast can you fix this?  We really need to get v1.10.1 out the door ASAP...

**Comment by jsquyres** [comment]
Arrgh -- I see we didn't credit dmt4 in the NEWS bullet, either.  That is easily fixed, though.

**Comment by ggouaillardet** [comment]
@bosilca the following simple program issue warnings with master

```c
#include <stdio.h>

#include <mpi.h>

int main(int argc, char *argv[]) {
    int rank;
    MPI_Datatype t1, type;
    int bl[2] = {1, 1};
    int ad[2] = {0, 2};

    MPI_Init(&argc, &argv);
    MPI_Comm_rank(MPI_COMM_WORLD, &rank);
    MPI_Type_indexed(2, bl, ad, MPI_INT, &t1);
    MPI_Type_commit(&t1);
    MPI_Type_create_resized(t1, 4, 16, &type);
    MPI_Type_commit(&type);

    if (0 == rank) {
        int buf[4] = {1, 2, 3, 4};
        MPI_Send(buf, 1, type, 1, 666, MPI_COMM_WORLD);
    } else if (1 == rank) {
        int buf[2] = {-1, -1};
        MPI_Recv(buf, 2, MPI_INT, 0, 666, MPI_COMM_WORLD, MPI_STATUS_IGNORE);
        if (2 != buf[0] || 4 != buf[1]) {
            fprintf(stderr, "expected {%d,%d}, got {%d,%d}\n", 2, 4, buf[0], buf[1]);
        }
    }

    MPI_Finalize();
    return 0;
}
```

there is no warning with mpich (not the latest mpich ...), except i get {1,3} instead of {2,4} (!)
one option is i just found a bug in mpich (!)
and an other one is i do not understand MPI_Type_create_resized, and ompi should not use ompi_datatype_create_resized in ompi_datatype_create_darray.

**Comment by gpapaure** [comment]
I think MPI_Type_create_resized is working (quite) right in your example.
From my understanding create_resized is used to "fake" a datatype layout, it doesn't "shift" the datatype. You can have the "real" layout with MPI_Type_get_true_extent.
Here is a new programm to do what you wanted on the first one
```
#include <stdio.h>
#include <mpi.h>

int main(int argc, char *argv[]) {
    int rank;
    MPI_Datatype t1, type, t2;
    int bl[2] = {1, 1};
    int ad[2] = {0, 2};
    int bl_hindexed[1] = {1};
    MPI_Aint ad_hindexed[1] = {4};
    MPI_Aint true_lb_t1,     true_lb_type;
    MPI_Aint true_extent_t1, true_extent_type;

    MPI_Init(&argc, &argv);
    MPI_Comm_rank(MPI_COMM_WORLD, &rank);
    MPI_Type_indexed(2, bl, ad, MPI_INT, &t1);
    MPI_Type_commit(&t1);
    MPI_Type_get_true_extent(t1, &true_lb_t1, &true_extent_t1);
    MPI_Type_create_resized(t1, 4, true_extent_t1, &type);
    MPI_Type_commit(&type);
    MPI_Type_get_true_extent(type, &true_lb_type, &true_extent_type);
    MPI_Type_create_hindexed(1, bl_hindexed, ad_hindexed, t1, &t2);
    MPI_Type_commit(&t2);

    if(true_lb_t1 != true_lb_type || true_extent_t1 != true_extent_type) {
        fprintf(stderr, "expected true_lb=%d true_extent=%d, got true_lb=%d true_extent=%d\n", true_lb_t1, true_extent_t1, true_lb_type, true_extent_type);
    }

    if (0 == rank) {
        int buf[4] = {1, 2, 3, 4};
        MPI_Send(buf, 1, t2, 1, 666, MPI_COMM_WORLD);
    } else if (1 == rank) {
        int buf[2] = {-1, -1};
        MPI_Recv(buf, 2, MPI_INT, 0, 666, MPI_COMM_WORLD, MPI_STATUS_IGNORE);
        if (2 != buf[0] || 4 != buf[1]) {
            fprintf(stderr, "expected {%d,%d}, got {%d,%d}\n", 2, 4, buf[0], buf[1]);
        }
    }

    MPI_Finalize();
    return 0;
}
```

I may be wrong but the true_lb of create_resized seems wrong in master.

**Comment by ggouaillardet** [comment]
@gpapaure i am fine with the latest assertion : create_resized is wrong in the master
here is a patch for that
```patch
diff --git a/opal/datatype/opal_datatype_resize.c b/opal/datatype/opal_datatype_resize.c
index 71347d0..b239c67 100644
--- a/opal/datatype/opal_datatype_resize.c
+++ b/opal/datatype/opal_datatype_resize.c
@@ -4,6 +4,8 @@
  *                         of Tennessee Research Foundation.  All rights
  *                         reserved.
  * Copyright (c) 2009      Oak Ridge National Labs.  All rights reserved.
+ * Copyright (c) 2015      Research Organization for Information Science
+ *                         and Technology (RIST). All rights reserved.
  * $COPYRIGHT$
  *
  * Additional copyrights may follow
@@ -21,9 +23,6 @@ int32_t opal_datatype_resize( opal_datatype_t* type, OPAL_PTRDIFF_TYPE lb, OPAL_
     type->lb = lb;
     type->ub = lb + extent;
 
-    type->true_lb += lb;
-    type->true_ub += lb;
-
     type->flags &= ~OPAL_DATATYPE_FLAG_NO_GAPS;
     if( (extent == (OPAL_PTRDIFF_TYPE)type->size) &&
         (type->flags & OPAL_DATATYPE_FLAG_CONTIGUOUS) ) {
```

with this patch, ompi and mpich behave the same, and there is no more warning in ompi.

@bosilca could you please comment on that ?

**Comment by rhc54** [comment]
@bosilca @ggouaillardet @gpapaure Hey folks, 1.10.1 is blocked for release on this issue. Any prognosis on when we will converge on a solution?

**Comment by gpapaure** [comment]
#1003 should solve this issue
Do you want me to make a new pr for 1.10 branch ?

**Comment by rhc54** [comment]
This should get committed to master first, and then new PRs for the 1.10 and 2.x branches should be filed. I'm not sure we have agreement yet on the patch, though, so we need someone to say this is correct.

@bosilca ?

**Comment by jsquyres** [comment]
Just some additional bookkeeping here:

* The initial fix on this ticket was brought to v1.10 in open-mpi/ompi-release@9f71ec601fd66f0b4c3b0575aef974ba9c6149b6 and open-mpi/ompi-release@769bd1154e5faf34ac28bda4c445b2bc0123ca54
* The initial fix on this ticket is not needed on v2.x (as of today, 19 Oct 2015).  I didn't track down how it got there, but when I cherry-pick the non-merge commit from above, it results in an empty set on v2.x.

If #1003 is, indeed, the solution to the second problem on this ticket, then it needs to be PRed to both v1.10 and v2.x.

I spoke to @bosilca; he's checking #1003.

**Comment by rhc54** [comment]
Can someone please clarify where we are on this one? I see that #1003 references some other ticket, and I confess I'm a bit confused.

This really is holding us up on 1.10.1, so I'd like to get it resolved if we can.

**Comment by ggouaillardet** [comment]
There are two issues here
- MPI_Type_create_{darray,subarray} are broken, and #1003 fixes that
- MPI_Type_create_resized does not work when lb is non zero, and my inline patch fixes that

since ddt is a sensitive topic, I think @bosilca should make the final decision on how to move forward.

**Comment by jsquyres** [comment]
@bosilca and I talked on the phone today about 1.10.1.

We agreed that the minimum distance fix should be brought to v1.10 so that 1.10.1 can be released.  @bosilca knows how to do this, and can do so in the immediate future.  Specifically: this fix is *correct*, but it isn't great from an holistic infrastructure point of view.  But it should be good enough for the v1.10 series.

The formal / forward-looking / holistic infrastructure-based fix can be done on master / v2.x.  @bosilca is still working on that.

@bosilca Can you clarify which issues / PRs need to move forward for v1.10.1?

**Comment by bosilca** [comment]
The corresponding issue for the devel version is #1063.

**Comment by bosilca** [comment]
The patch proposed in #1003 should go in 1.10.1
